
mcp23017:
  - id: 'mcp_outputs_1to16'
    i2c_id: bus_b
    address: 0x21
  - id: 'mcp_outputs_17to32'
    i2c_id: bus_b
    address: 0x20

switch:
  - platform: gpio
    id: cover_open_01
    pin:
      mcp23xxx: mcp_outputs_1to16
      number: 0
      mode: OUTPUT
    interlock: &cover_interlock_01 [cover_open_01, cover_close_01]
    restore_mode: always off

  - platform: gpio
    id: cover_close_01
    pin:
      mcp23xxx: mcp_outputs_1to16
      number: 1
      mode: OUTPUT
    interlock: *cover_interlock_01
    restore_mode: always off

  - platform: gpio
    id: cover_open_02
    pin:
      mcp23xxx: mcp_outputs_1to16
      number: 2
      mode: OUTPUT
    interlock: &cover_interlock_02 [cover_open_02, cover_close_02]
    restore_mode: always off

  - platform: gpio
    id: cover_close_02
    pin:
      mcp23xxx: mcp_outputs_1to16
      number: 3
      mode: OUTPUT
    interlock: *cover_interlock_02
    restore_mode: always off

  - platform: gpio
    id: cover_open_03
    pin:
      mcp23xxx: mcp_outputs_1to16
      number: 4
      mode: OUTPUT
    interlock: &cover_interlock_03 [cover_open_03, cover_close_03]
    restore_mode: always off

  - platform: gpio
    id: cover_close_03
    pin:
      mcp23xxx: mcp_outputs_1to16
      number: 5
      mode: OUTPUT
    interlock: *cover_interlock_03
    restore_mode: always off

  - platform: gpio
    id: cover_open_04
    pin:
      mcp23xxx: mcp_outputs_1to16
      number: 6
      mode: OUTPUT
    interlock: &cover_interlock_04 [cover_open_04, cover_close_04]
    restore_mode: always off

  - platform: gpio
    id: cover_close_04
    pin:
      mcp23xxx: mcp_outputs_1to16
      number: 7
      mode: OUTPUT
    interlock: *cover_interlock_04
    restore_mode: always off

  - platform: gpio
    id: cover_open_05
    pin:
      mcp23xxx: mcp_outputs_1to16
      number: 8
      mode: OUTPUT
    interlock: &cover_interlock_05 [cover_open_05, cover_close_05]
    restore_mode: always off

  - platform: gpio
    id: cover_close_05
    pin:
      mcp23xxx: mcp_outputs_1to16
      number: 9
      mode: OUTPUT
    interlock: *cover_interlock_05
    restore_mode: always off

  - platform: gpio
    id: cover_open_06
    pin:
      mcp23xxx: mcp_outputs_1to16
      number: 10
      mode: OUTPUT
    interlock: &cover_interlock_06 [cover_open_06, cover_close_06]
    restore_mode: always off

  - platform: gpio
    id: cover_close_06
    pin:
      mcp23xxx: mcp_outputs_1to16
      number: 11
      mode: OUTPUT
    interlock: *cover_interlock_06
    restore_mode: always off

  - platform: gpio
    id: cover_open_07
    pin:
      mcp23xxx: mcp_outputs_1to16
      number: 12
      mode: OUTPUT
    interlock: &cover_interlock_07 [cover_open_07, cover_close_07]
    restore_mode: always off

  - platform: gpio
    id: cover_close_07
    pin:
      mcp23xxx: mcp_outputs_1to16
      number: 13
      mode: OUTPUT
    interlock: *cover_interlock_07
    restore_mode: always off

  - platform: gpio
    id: cover_open_08
    pin:
      mcp23xxx: mcp_outputs_1to16
      number: 14
      mode: OUTPUT
    interlock: &cover_interlock_08 [cover_open_07, cover_close_07]
    restore_mode: always off

  - platform: gpio
    id: cover_close_08
    pin:
      mcp23xxx: mcp_outputs_1to16
      number: 15
      mode: OUTPUT
    interlock: *cover_interlock_08
    restore_mode: always off

  - platform: gpio
    id: cover_open_09
    pin:
      mcp23xxx: mcp_outputs_17to32
      number: 0
      mode: OUTPUT
    interlock: &cover_interlock_09 [cover_open_07, cover_close_07]
    restore_mode: always off

  - platform: gpio
    id: cover_close_09
    pin:
      mcp23xxx: mcp_outputs_17to32
      number: 1
      mode: OUTPUT
    interlock: *cover_interlock_09
    restore_mode: always off

  - platform: gpio
    id: cover_open_10
    pin:
      mcp23xxx: mcp_outputs_17to32
      number: 2
      mode: OUTPUT
    interlock: &cover_interlock_10 [cover_open_07, cover_close_07]
    restore_mode: always off

  - platform: gpio
    id: cover_close_10
    pin:
      mcp23xxx: mcp_outputs_17to32
      number: 3
      mode: OUTPUT
    interlock: *cover_interlock_10
    restore_mode: always off

  - platform: gpio
    id: cover_open_11
    pin:
      mcp23xxx: mcp_outputs_17to32
      number: 4
      mode: OUTPUT
    interlock: &cover_interlock_11 [cover_open_07, cover_close_07]
    restore_mode: always off

  - platform: gpio
    id: cover_close_11
    pin:
      mcp23xxx: mcp_outputs_17to32
      number: 5
      mode: OUTPUT
    interlock: *cover_interlock_11
    restore_mode: always off

  - platform: gpio
    id: cover_open_12
    pin:
      mcp23xxx: mcp_outputs_17to32
      number: 6
      mode: OUTPUT
    interlock: &cover_interlock_12 [cover_open_07, cover_close_07]
    restore_mode: always off

  - platform: gpio
    id: cover_close_12
    pin:
      mcp23xxx: mcp_outputs_17to32
      number: 7
      mode: OUTPUT
    interlock: *cover_interlock_12
    restore_mode: always off

  - platform: gpio
    id: cover_open_13
    pin:
      mcp23xxx: mcp_outputs_17to32
      number: 8
      mode: OUTPUT
    interlock: &cover_interlock_13 [cover_open_07, cover_close_07]
    restore_mode: always off

  - platform: gpio
    id: cover_close_13
    pin:
      mcp23xxx: mcp_outputs_17to32
      number: 9
      mode: OUTPUT
    interlock: *cover_interlock_13
    restore_mode: always off

  - platform: gpio
    id: cover_open_14
    pin:
      mcp23xxx: mcp_outputs_17to32
      number: 10
      mode: OUTPUT
    interlock: &cover_interlock_14 [cover_open_07, cover_close_07]
    restore_mode: always off

  - platform: gpio
    id: cover_close_14
    pin:
      mcp23xxx: mcp_outputs_17to32
      number: 11
      mode: OUTPUT
    interlock: *cover_interlock_14
    restore_mode: always off

  - platform: gpio
    id: cover_open_15
    pin:
      mcp23xxx: mcp_outputs_17to32
      number: 12
      mode: OUTPUT
    interlock: &cover_interlock_15 [cover_open_07, cover_close_07]
    restore_mode: always off

  - platform: gpio
    id: cover_close_15
    pin:
      mcp23xxx: mcp_outputs_17to32
      number: 13
      mode: OUTPUT
    interlock: *cover_interlock_15
    restore_mode: always off

  - platform: gpio
    id: cover_open_16
    pin:
      mcp23xxx: mcp_outputs_17to32
      number: 14
      mode: OUTPUT
    interlock: &cover_interlock_16 [cover_open_07, cover_close_07]
    restore_mode: always off

  - platform: gpio
    id: cover_close_16
    pin:
      mcp23xxx: mcp_outputs_17to32
      number: 15
      mode: OUTPUT
    interlock: *cover_interlock_16
    restore_mode: always off

# example
# relay
#  - platform: gpio
#    id: relay_13
#    pin:
#      mcp23xxx: mcp_outputs_17to32
#      number: 4
#      mode:
#        output: true
#      inverted: false


