esphome:
  name: ${node_name}
  platform: ESP32
  board: nodemcu-32s

i2c:
  - id: bus_a
    sda: GPIO14
    scl: GPIO15
    scan: True
    frequency: 400kHz
  - id: bus_b
    sda: GPIO17
    scl: GPIO33
    scan: True
    frequency: 400kHz

ethernet:
  id: eth
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO0_IN
  phy_addr: 1
  power_pin: GPIO16
