substitutions:
  node_name: boneio
  dir_name: './'

packages:
  # devices
  core: !include devices/wt32_eth01.yaml
  internals: !include devices/boneio_board.yaml
  temp: !include devices/lm75b.yaml
  display: !include devices/display.yaml
  # uart: !include devices/uart.yaml
  # one_wire: !include devices/one_wire.yaml
  # relay32
  # output: !include boards/relay32_outputs_PCF.yaml #or MCP
  # input: !include boards/relay32_inputs_PCF.yaml #or MCP
  # dimmer led
  output: !include boards/dimmer_led8x4_outputs.yaml
  # input: !include boards/dimmer_led8x4_inputs.yaml
  light: !include boards/monochromatic_lights.yaml
  # cover
  #  output: !include boneio/boards/cover16_outputs_MCP_old.yaml
  #  output: !include boneio/boards/cover16_outputs.yaml
  # input: !include boneio/boards/cover16_inputs.yaml
  # input: !include boneio/boards/cover16_inputs_PCF.yaml
  # cover: !include boneio/boards/cover.yaml
  # mosfet
  # output: !include boards/mosfet48_outputs_PCF.yaml 

logger:
  baud_rate: 0
api:
ota:
  password: boneio
# disable web server - for testing only
web_server:
  port: 80
  local: true

time:
  - platform: homeassistant
    timezone: Europe/Warsaw
    id: homeassistant_time
    # instead try to synchronize via network repeatedly ...
    on_time_sync:
      then:
        # ... and update the RTC when the synchronization was successful
        ds1307.write_time:
